### ISSUE TITLE
[Question] Hiding the tab bar controller after a push segue

### ISSUE THREAD

**Issue by mirceamironenco** [mwhuss/MHVerticalTabBarController#1]
Is changing the entire frame ok ? Seems to work fine, just wanted your opinion .

**Comment by mwhuss** [comment]
I was using this the same way with some custom panel view controllers. The way I was handling it was changing the frame of the entire `MHVerticalTabBarController` view. I think a `-hide:animated:` method would be a welcome addition if you'd like to send a PR.
